language: java
before_install:
- chmod +x gradlew
jdk:
- openjdk8
dist: trusty
sudo: false
addons:
  sonarqube:
    organization: kayvee83-github
    token:
      secure: rE3SonXffz7u/dZzs2m2g5xubQDOmC9e1AVMrtVxSNXCq0YC2rbAzq06bDPBQfwwS1gRMqq6Vnl7h3L+mc0dESRyEjA1gxmQtvmloJ8tSYMCUxhgPiIVtA6SeMF3s5xr2lw/nRgpdBBWHsX12rFBXLCbHCDnwL25MoEGMXKhX4+HKyoJJ3KypLLigCccA
        ZmjDKnc55WZUtAbMmFyIh6UE37WIx3xTiNUHn9n4EgQArOSfkIeVC5jkporda+aAPfUfDZZVjf6Dn1+mtpMRS84iZ6mfLcC1D6MWtKWJrZH/F5doi57TmErn82ORzqwqZOfGvfrGAK4EuYcwUNP6HFRj+J6Z2h5Ti/XiqxplmvHUeUB05EqXzpZwDSYTAfCVkWEVHmSd
        SfMQHYlhG9FtSKF9n+0gZt89Bck2y1oR0WPQsQRL9rgNqqV97+wKAzTLHbGsMxp0db4Tnh4yahPvWoFT7bCbAXQFhPMepBEDAf/P6Oz+2RbM5Z05o5Mfiq9oisMTH03vma5UCuuj7ZL+ko1nGWwEoHcKb6oueHFBNIg87UxlGLkk8DQyFFyvVgG++AOZrqRic1haYZe4
        YMYJ1HXZ8pEopWjt9Z//Fcibk66z+t+0rgFK03B3cYmWhZvQsgMfz702aOh42Y+ol1RadoOPhPWomQoGl6lYa38dWOuFH4=
    branches:
    - master
script:
- "./gradlew sonarqube"
deploy:
  provider: heroku
  api_key:
    secure: ZarCgFJXlFj1Aug3xVPLiHQkQENH2urJ7bl3htGe8CSjwe4gRpGi3mAnbFJ9HltKXnv2jgxFPr0/jxEfXLn21bP+RP/yeNDc+Bo17bapZUeLpJuiwMEFqe+6+Oq9qLHklyEJxOdDB6wtfFyl05MFukQ/gGQ2CJ5gb2sthCtgnS9hSa6e+pNAQNW5YhZ8IaqFKKzrUHqtNKGLbnIER+yAUdnkyMr4s4+Pqhz7SonB4vX00hd5CjtW3XRMwSvDF00QIoGJKFxy0Gs52gqxWcwY66ijIDfbzk68CGB1YaE1NUiFvbKwLC3aAk/WZHiutVrN7Sdjkg2CKtsN5lZVOTLY4n58k7Kiqy69pKArkd4puvMB0Z0nOGq1t021Y846vsKZs24X98DCwGNUlYWteyjPz4Fza6FNcJsBtlN2QUB7D0whEvMN680vrEb5qmFKJgkg5yxceNseVRsBVoBY3wrMrGWIjb8DekyEhOPEOATVEtLhQ7PVOm1ZythKX4sY0ktZre+qnUjA7BcGk++5Rgrqy7nXkJ5OlcMR56byKFIav8adTMI9AYPOxF5YGl2i4Y3h+ArCy1zFFziV+qOpfR2jtaQBFrFkQHGiZuuiK7ltUsdWnuZmAChk1RBzFrVuXNRZbkDERBK0a+zlqimgMWr6gbDnHceM+cuKBSb8EZL4QTc=
  app: helloworldkv
