language: java
before_install:
- chmod +x gradlew
jdk:
- openjdk8
dist: trusty
sudo: false
addons:
  sonarcloud:
    organization: kayvee83-github
    token:
        secure: "fEPtGL2NQPZ28u+6+ngbbK/qp+TO1hDreOuZRZDPlVyOkznvepmfhiAmdv8eIpNLMaR5zzXqtgsakQzXSjwfF1UmdZKXn1M3HEadsd0JiA4/eai++jzrvy70Ny32XGzAUzDqNlefsXhZs85H9Wc+b1VTc9HILv+HkXnxESKPUZ2fNhctpjdUjYwrfF85q
S6mNKOg6rkxHhq5xMlVDqT/qlSE8AP9UtH3ppjwt95VE9ww6PHl9fQqJIUbp/7IaX0TVB6STpJrrkj3Zwem+Afl2B8s4m5E16x/9DndBVxW/5ly1QwITLcz+LU4d6cq+5Rvu7QJv0zEselEspgu9FLKNteRSDhP90bXbgJQnBQA5xduilgAcSJkv7e3wtoAqZmRsPTTh
zHZ1c2BIIRFKTeVwlAN3ABOjhWCFo0AK15Nvlwlarbtyd2f7PHwRxvSX8pc5aPLN8rWxkvRoh7VdB29WD8yf/8hOj2vmA1AaGSybNqerBCpuT//zNySPZQZxBdHLs8+ZzqF93+U4X4Iz4LZn0x1sQDCb/XReLkrTHtP8CSoSLQiMOmNHVmOcvo2nLwOriNOIC/+ZhRPV
S7jG1CRv/bGlTiU9+nsRZck/fPW96ERnW7pLlUak+ENzGsazITgbMN1w64cPOum/tXUNRl2dyvQ8C6JC1blufocLNM7mes="
    branches:
    - master
script:
 - sonar-scanner
deploy:
  provider: heroku
  api_key:
    secure: ZarCgFJXlFj1Aug3xVPLiHQkQENH2urJ7bl3htGe8CSjwe4gRpGi3mAnbFJ9HltKXnv2jgxFPr0/jxEfXLn21bP+RP/yeNDc+Bo17bapZUeLpJuiwMEFqe+6+Oq9qLHklyEJxOdDB6wtfFyl05MFukQ/gGQ2CJ5gb2sthCtgnS9hSa6e+pNAQNW5YhZ8IaqFKKzrUHqtNKGLbnIER+yAUdnkyMr4s4+Pqhz7SonB4vX00hd5CjtW3XRMwSvDF00QIoGJKFxy0Gs52gqxWcwY66ijIDfbzk68CGB1YaE1NUiFvbKwLC3aAk/WZHiutVrN7Sdjkg2CKtsN5lZVOTLY4n58k7Kiqy69pKArkd4puvMB0Z0nOGq1t021Y846vsKZs24X98DCwGNUlYWteyjPz4Fza6FNcJsBtlN2QUB7D0whEvMN680vrEb5qmFKJgkg5yxceNseVRsBVoBY3wrMrGWIjb8DekyEhOPEOATVEtLhQ7PVOm1ZythKX4sY0ktZre+qnUjA7BcGk++5Rgrqy7nXkJ5OlcMR56byKFIav8adTMI9AYPOxF5YGl2i4Y3h+ArCy1zFFziV+qOpfR2jtaQBFrFkQHGiZuuiK7ltUsdWnuZmAChk1RBzFrVuXNRZbkDERBK0a+zlqimgMWr6gbDnHceM+cuKBSb8EZL4QTc=
  app: helloworldkv
